language: ruby

sudo: false

rvm:
  - 2.2.4

env:
  - RAILS=4-2-stable DB=postgres

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres

branches:
  only:
    - rails424ruby224
